//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.08
// Generated on Monday, December 1, 2025 8:06:35  PM

#include <string>

#include "configs/MechanismConfigKitBot_2025.h"
#include "configs/MechanismConfigMgr.h"
#include "configs/RobotElementNames.h"
#include "utils/logging/debug/Logger.h"
#include "utils/PeriodicLooper.h"

using std::string;

void MechanismConfigKitBot_2025::DefineMechanisms()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("Delivery"), "");
	m_theDelivery = new Delivery(RobotIdentifier::KIT_BOT_2025);
	m_theDelivery->CreateKitBot2025();
	m_theDelivery->CreateAndRegisterStates();
	m_theDelivery->InitializeKitBot2025();
	m_theDelivery->Init(/*m_theDelivery*/);
	m_mechanismMap[MechanismTypes::MECHANISM_TYPE::DELIVERY] = m_theDelivery;

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("Initializing mechanism"), string("Climber"), "");
	m_theClimber = new Climber(RobotIdentifier::KIT_BOT_2025);
	m_theClimber->CreateKitBot2025();
	m_theClimber->CreateAndRegisterStates();
	m_theClimber->InitializeKitBot2025();
	m_theClimber->Init(/*m_theClimber*/);
	m_mechanismMap[MechanismTypes::MECHANISM_TYPE::CLIMBER] = m_theClimber;
}

StateMgr *MechanismConfigKitBot_2025::GetMechanism(MechanismTypes::MECHANISM_TYPE mechType)
{
	auto itr = m_mechanismMap.find(mechType);
	if (itr != m_mechanismMap.end())
	{
		return itr->second;
	}
	return nullptr;
}

void MechanismConfigKitBot_2025::DefineLEDs()
{
}