//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.08
// Generated on Monday, December 1, 2025 8:06:35  PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configs.hpp"

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

class Climber : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_MANUAL_CLIMB
	};

	Climber(RobotIdentifier activeRobotId);
	Climber() = delete;
	~Climber() = default;

	void CreateKitBot2025();
	void InitializeKitBot2025();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetClimberPrecentOut(double percentOut)
	{
		m_ClimberPrecentOut.Output = percentOut;
		m_ClimberActiveTarget = &m_ClimberPrecentOut;
	}
	void UpdateTargetCharlieBoxPrecentOut(double percentOut)
	{
		m_CharlieBoxPrecentOut.Output = percentOut;
		m_CharlieBoxActiveTarget = &m_CharlieBoxPrecentOut;
	}

	virtual bool IsAtMinPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;
	virtual bool IsAtMaxPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog() override;

	bool IsClimbMode() const { return m_climbMode == RobotStateChanges::ClimbMode::ClimbModeOn; }
	void NotifyStateUpdate(RobotStateChanges::StateChange stchange, int value) override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetClimber() const { return m_Climber; }
	ctre::phoenix6::hardware::TalonFX *GetCharlieBox() const { return m_CharlieBox; }
	ControlData *GetPrecentOut() const { return m_PrecentOut; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_Climber;
	ctre::phoenix6::hardware::TalonFX *m_CharlieBox;
	ControlData *m_PrecentOut;

	RobotStateChanges::ClimbMode m_climbMode;

	void InitializeTalonFXClimberKitBot2025();
	void InitializeTalonFXCharlieBoxKitBot2025();

	ctre::phoenix6::controls::DutyCycleOut m_ClimberPrecentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_CharlieBoxPrecentOut{0.0};
	ctre::phoenix6::controls::ControlRequest *m_ClimberActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_CharlieBoxActiveTarget;

	// void InitializeLogging();
};