//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.08
// Generated on Monday, December 1, 2025 8:06:35  PM

#include <string>

// FRC Includes
#include <networktables/NetworkTableInstance.h>
#include <frc/Timer.h>

#include "Climber.h"
#include "utils/logging/debug/Logger.h"
#include "utils/PeriodicLooper.h"
#include "state/RobotState.h"
#include "utils/DragonPower.h"

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configs.hpp"
#include "mechanisms/Climber/OffState.h"
#include "mechanisms/Climber/ManualClimbState.h"

using ctre::phoenix6::configs::Slot0Configs;
using ctre::phoenix6::configs::Slot1Configs;
using ctre::phoenix6::configs::TalonFXConfiguration;
using ctre::phoenix6::signals::FeedbackSensorSourceValue;
using ctre::phoenix6::signals::ForwardLimitSourceValue;
using ctre::phoenix6::signals::ForwardLimitTypeValue;
using ctre::phoenix6::signals::GravityTypeValue;
using ctre::phoenix6::signals::InvertedValue;
using ctre::phoenix6::signals::NeutralModeValue;
using ctre::phoenix6::signals::ReverseLimitSourceValue;
using ctre::phoenix6::signals::ReverseLimitTypeValue;
using ctre::phoenix6::signals::StaticFeedforwardSignValue;

using std::string;
using namespace ClimberStates;

void Climber::CreateAndRegisterStates()
{
	OffState *OffStateInst = new OffState(string("Off"), 0, this, m_activeRobotId);
	AddToStateVector(OffStateInst);

	ManualClimbState *ManualClimbStateInst = new ManualClimbState(string("ManualClimb"), 1, this, m_activeRobotId);
	AddToStateVector(ManualClimbStateInst);

	OffStateInst->RegisterTransitionState(ManualClimbStateInst);
	ManualClimbStateInst->RegisterTransitionState(OffStateInst);
}

Climber::Climber(RobotIdentifier activeRobotId) : BaseMech(MechanismTypes::MECHANISM_TYPE::CLIMBER, std::string("Climber")),
												  m_activeRobotId(activeRobotId),
												  m_stateMap(),
												  m_climbMode(RobotStateChanges::ClimbMode::ClimbModeOff)

{
	PeriodicLooper::GetInstance()->RegisterAll(this);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::ClimbModeStatus_Int);
	// InitializeLogging();
}

/* void Climber::InitializeLogging()
 {
	wpi::log::DataLog &log = frc::DataLogManager::GetLog();

	 m_ClimberTotalEnergyLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/TotalEnergy");
m_ClimberTotalEnergyLogEntry.Append(0.0);
m_ClimberTotalWattHoursLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/TotalWattHours");
m_ClimberTotalWattHoursLogEntry.Append(0.0);
m_ClimberLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/ClimberPosition");
m_ClimberLogEntry.Append(0.0);
m_ClimberTargetLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/ClimberTarget");
m_ClimberTargetLogEntry.Append(0.0);
m_ClimberPowerLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/ClimberPower");
m_ClimberPowerLogEntry.Append(0.0);
m_ClimberEnergyLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/ClimberEnergy");
m_ClimberEnergyLogEntry.Append(0.0);
m_CharlieBoxLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/CharlieBoxPosition");
m_CharlieBoxLogEntry.Append(0.0);
m_CharlieBoxTargetLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/CharlieBoxTarget");
m_CharlieBoxTargetLogEntry.Append(0.0);
m_CharlieBoxPowerLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/CharlieBoxPower");
m_CharlieBoxPowerLogEntry.Append(0.0);
m_CharlieBoxEnergyLogEntry = wpi::log::DoubleLogEntry(log, "mechanisms/Climber/CharlieBoxEnergy");
m_CharlieBoxEnergyLogEntry.Append(0.0);
m_ClimberStateLogEntry = wpi::log::IntegerLogEntry(log, "mechanisms/Climber/State");
m_ClimberStateLogEntry.Append(0);
 }*/

std::map<std::string, Climber::STATE_NAMES>
	Climber::stringToSTATE_NAMESEnumMap{
		{"STATE_OFF", Climber::STATE_NAMES::STATE_OFF},
		{"STATE_MANUAL_CLIMB", Climber::STATE_NAMES::STATE_MANUAL_CLIMB},
	};

void Climber::CreateKitBot2025()
{
	m_ntName = "Climber";
	m_Climber = new ctre::phoenix6::hardware::TalonFX(0, "rio");
	m_CharlieBox = new ctre::phoenix6::hardware::TalonFX(6, "rio");

	m_PrecentOut = new ControlData(
		ControlModes::CONTROL_TYPE::PERCENT_OUTPUT,		  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_PrecentOut",									  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::VOLTAGE,					 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);

	ReadConstants("Climber.xml", 2025);
}

void Climber::InitializeKitBot2025()
{
	InitializeTalonFXClimberKitBot2025();
	InitializeTalonFXCharlieBoxKitBot2025();
}
void Climber::InitializeTalonFXClimberKitBot2025()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(0);
	configs.CurrentLimits.StatorCurrentLimitEnable = false;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = false;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.OpenLoopRamps.VoltageOpenLoopRampPeriod = units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_Climber->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_Climber", "m_Climber Status", status.GetName());
}

void Climber::InitializeTalonFXCharlieBoxKitBot2025()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(0);
	configs.CurrentLimits.StatorCurrentLimitEnable = false;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(0);
	configs.CurrentLimits.SupplyCurrentLimitEnable = false;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(0);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.OpenLoopRamps.VoltageOpenLoopRampPeriod = units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_CharlieBox->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_CharlieBox", "m_CharlieBox Status", status.GetName());
}

void Climber::SetCurrentState(int state, bool run)
{
	StateMgr::SetCurrentState(state, run);
}

void Climber::RunCommonTasks()
{
	// This function is called once per loop before the current state Run()
	Cyclic();
}

/// @brief  Set the control constants (e.g. PIDF values).
/// @param [in] ControlData*                                   pid:  the control constants
/// @return void
void Climber::SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier, int slot, ControlData pid)
{
}

/// @brief update the output to the mechanism using the current controller and target value(s)
/// @return void
void Climber::Update()
{
	m_Climber->SetControl(*m_ClimberActiveTarget);
	m_CharlieBox->SetControl(*m_CharlieBoxActiveTarget);
}

bool Climber::IsAtMinPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const
{
	// auto motor = GetMotorMech(identifier);
	// if (motor != nullptr)
	// {
	//     return motor->IsAtMinTravel();
	// }
	return false;
}

bool Climber::IsAtMaxPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const
{
	// auto motor = GetMotorMech(identifier);
	// if (motor != nullptr)
	// {
	//     return motor->IsAtMaxTravel();
	// }
	return false;
}

void Climber::Cyclic()
{
	Update();
}

ControlData *Climber::GetControlData(string name)
{
	if (name.compare("PrecentOut") == 0)
		return m_PrecentOut;

	return nullptr;
}

void Climber::NotifyStateUpdate(RobotStateChanges::StateChange statechange, int value)
{
	if (statechange == RobotStateChanges::StateChange::ClimbModeStatus_Int)
	{
		m_climbMode = static_cast<RobotStateChanges::ClimbMode>(value);
	}
}

/* void Climber::DataLog(uint64_t timestamp)
{
   auto currTime = m_powerTimer.Get();
LogClimber(timestamp, m_Climber->GetPosition().GetValueAsDouble());
auto ClimberPower = DragonPower::CalcPowerEnergy(currTime, m_Climber->GetSupplyVoltage().GetValueAsDouble(), m_Climber->GetSupplyCurrent().GetValueAsDouble());
m_power = get<0>(ClimberPower);
m_energy = get<1>(ClimberPower);
m_totalEnergy += m_energy;
LogClimberPower(timestamp, m_power);
LogClimberEnergy(timestamp, m_energy);
LogCharlieBox(timestamp, m_CharlieBox->GetPosition().GetValueAsDouble());
auto CharlieBoxPower = DragonPower::CalcPowerEnergy(currTime, m_CharlieBox->GetSupplyVoltage().GetValueAsDouble(), m_CharlieBox->GetSupplyCurrent().GetValueAsDouble());
m_power = get<0>(CharlieBoxPower);
m_energy = get<1>(CharlieBoxPower);
m_totalEnergy += m_energy;
LogCharlieBoxPower(timestamp, m_power);
LogCharlieBoxEnergy(timestamp, m_energy);
LogClimberState(timestamp, GetCurrentState());
m_totalWattHours += DragonPower::ConvertEnergyToWattHours(m_totalEnergy);
LogClimberTotalEnergy(timestamp, m_totalEnergy);
LogClimberTotalWattHours(timestamp, m_totalWattHours);
m_powerTimer.Reset();
m_powerTimer.Start();
 }*/